title: Ken Lapain & Sons
author:
  name: Ken Lapain & Sons
  email: jodie@lapain.ca
description: > # this means to ignore newlines until "show_excerpts:"
  Located in the hub of Essex County at 2119 County Road 15 in Essex, Ken Lapain & Sons is the one-stop shop for all your service and repair needs.

show_excerpts: false # set to true to show excerpts on the homepage

logo: lapain-logo.png
logo_white: lapain-logo.png
logo_dark: lapain-logo.png

# facebook: https://www.facebook.com/windsorhydrovac/
# instagram: https://www.instagram.com/hurricane_hydrovac_servicesinc/

sass:
  load_paths:
    - node_modules
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
exclude:
  - package.json
  - README.md
  - LICENSE.txt
  - yarn.lock
  - _compress_images_cache.yml
  
# Build settings
theme: hurricane-theme
skin: lapain

plugins:
 - jekyll-seo-tag

phone:
 - 519.776.6473