title: Lapain & Sons
author:
  name: Lapain & Sons
  email: info@thehurricanegroup.com
description: > # this means to ignore newlines until "show_excerpts:"
  Providing the Windsor Region with unparalleled service in the sanitation and excavation industries.

show_excerpts: false # set to true to show excerpts on the homepage

logo: lapain-logo.png
logo_white: lapain-logo.png
logo_dark: lapain-logo.png

# facebook: https://www.facebook.com/windsorhydrovac/
# instagram: https://www.instagram.com/hurricane_hydrovac_servicesinc/

sass:
  load_paths:
    - node_modules
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
exclude:
  - package.json
  - README.md
  - LICENSE.txt
  - yarn.lock
  
# Build settings
theme: hurricane-theme
skin: lapain

plugins:
 - jekyll-seo-tag

phone:
 - 519.776.6473